### ISSUE TITLE
[FR] Unknown Handling

### ISSUE THREAD

**Issue by Norien** [custom-cards/bignumber-card#1]
If roomba goes offline the style of my card is broken as the value will no longer fit.

If we could add a text value to handle errors this would help!

```
              - type: custom:bignumber-card
                entity: sensor.battery_roomba
                scale: 12px
                from: left
                min: 0
                max: 100
                severity:
                - value: 30
                  style: 'var(--label-badge-red)'
                - value: 70
                  style: 'var(--label-badge-yellow)'
                - value: 100
                  style: 'var(--label-badge-green)'
                - value: 'Unknown'
                  style: 'var(--label-badge-red)'
```
![Capture](https://user-images.githubusercontent.com/8930713/57982862-d30a9280-7a18-11e9-87d0-cf15d86de2a6.PNG)

~ Thanks for all you do!
