### ISSUE TITLE
Hideunit don't work

### ISSUE THREAD

**Issue by seventhsite** [custom-cards/bignumber-card#21]
I have "hideunit" set to true, but unit shown anyway.

Example of one my entity config:

```
             - type: custom:bignumber-card
               title: 40 /
               entity: sensor.glances_used
               scale: 20px
               from: bottom
               min: 0
               max: 40
               hideunit: true
               color: '#000000'
               bnStyle: 'var(--label-badge-blue)'
               severity:
                 - value: 33
                   bnStyle: 'var(--label-badge-green)'
                 - value: 35
                   bnStyle: 'var(--label-badge-yellow)'
                 - value: 37
                   bnStyle: 'var(--label-badge-red)'
                   color: '#FFFFFF'
```

 
![](https://habrastorage.org/webt/tu/wp/sc/tuwpsckg47lc2j8zvo67qgoopke.png)
