### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by hartitman** [custom-cards/bignumber-card#39]
Hi,

Can font sizes for both name/title and state/unit code be added so these can be changed.

Thank you

**Comment by igorsantos07** [comment]
Yep, that gets a bit complicated when you try to make different layouts with different bar sizes and text goes awry...

Either too small
![image](https://github.com/custom-cards/bignumber-card/assets/532299/ff6e4483-6b16-4362-81ad-4e76a0d55b28)

Or going over the scale size (40px in this example)
![image](https://github.com/custom-cards/bignumber-card/assets/532299/f55f2d48-628f-4ed9-b379-73dc3144855a)

**Comment by DeFlanko** [comment]
![image](https://github.com/custom-cards/bignumber-card/assets/5233969/e3584c2e-2344-41f0-b6a9-5d21ba2d41b5)
Adding to this post, seemed relevant. 

Using System bridge to capture my Host CPU core data, then using big number card to display the core cpu data to match that layout you'd normally see in Task Manager gets me this view. 

It works, but Im looking for a way to keep the same sized box scale, but literally shrink the font size by 50%
I have tried:
```yaml
type: custom:bignumber-card
min: 0
max: 100
entity: sensor.load_cpu_0
color: cornflowerblue
from: bottom
scale: 30px
card_mod:
  style: |
    ha-card {
      font-size: 10px;
    }
```
_But card-mod only works on cards that contain a ha-card element. This includes almost every card which can be seen, but not e.g. conditional, entity_filter, vertical-stack, horizontal-stack, grid._

which these cards are in a vertical can horizonal stacks to produce the layout.
