### ISSUE TITLE
bignumber-card backgound colour on iosipad & chrome dissapears when max value exceeded

### ISSUE THREAD

**Issue by peterhoe** [custom-cards/bignumber-card#7]
when defined max value in big number card is exceeded, red colour dissapears on ipad chrome browser.

functions as expected on windows 10, android, & macos 10.15.1

affected versions.
IOS 13.2.2
using chrome v 78.0.3904.84

if as per below example max value of 1500 is exceeded, background colour becomes transparent on ios ipad.

If the max value is increased, background colour displays untill max value is exceeded, then background colour becomes transparent

entity entry in ui-lovelace.yaml

```
- type: custom:bignumber-card
  title: Daikin Load
  entity: sensor.iotawatt_channel_2_acdaikin
  scale: 25px
  from: left
  min: 50
  max: 1500
  severity:
    - value: 50
      style: '#0dff35'
    - value: 620
      style: 'var(--label-badge-blue)'
    - value: 1360
      style: 'var(--label-badge-yellow)'
    - value: 3900
      style: 'var(--label-badge-red)'
```

resources entry in ui-lovelace.yaml

```
resources:
  - url: /local/bignumber-card.js?v=1
    type: js
```

result ios
![68534324-69e05800-0387-11ea-98dc-2482abcbbe8c](https://user-images.githubusercontent.com/36558013/68541773-c1b6a780-03f7-11ea-9de4-371ddd170a37.jpg)

result win10
![big-number-card-win10](https://user-images.githubusercontent.com/36558013/68534329-76fd4700-0387-11ea-9f01-e8b9fbb7dd71.jpg)
